language: php
php:
  - nightly
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
before_install:
  - gem install mime-types --version "< 3"
  - gem install --conservative mailcatcher > /dev/null 2>&1
  - mailcatcher
  # Temporary workaround for https://github.com/sj26/mailcatcher/issues/182
  - mailcatcher -f > out.txt&
  - echo "sendmail_path = /usr/bin/env catchmail -f some@from.address" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update
  - php vendor/bin/codecept build

script:
  - php vendor/bin/codecept run acceptance -d
  - php vendor/bin/codecept run unit --coverage-xml -d
